name: ci

on:
  workflow_dispatch:
    #push:
    #branches: [master]
    #pull_request:
    #branches: [master]
    #schedule:
    #- cron: 0 0 * * *

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jenkins-agent-dind

    steps:
      - name: Check envs
        run: |
          echo ${{ env }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:slim
            ${{ github.repository }}:latest

